/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_SAG;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Allisson Castro
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        Cargarg ch = new Empleados.Cargarg();
        ComboGeneroE.setModel(ch.getvalues());
        CargarSucursal cs = new Empleados.CargarSucursal();
        ComboSucursalE.setModel(cs.getvalues());
        CargarTDocumento ct = new Empleados.CargarTDocumento();
        ComboDocumento.setModel(ct.getvalues());
        cargartabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboSucursalE = new javax.swing.JComboBox<>();
        ComboDocumento = new javax.swing.JComboBox<>();
        BotonCargoHistoricoE = new javax.swing.JLabel();
        BotonSueldoHistoricoE = new javax.swing.JLabel();
        BotonEditarE = new javax.swing.JLabel();
        BotonAgregarE = new javax.swing.JLabel();
        BotonBuscarE = new javax.swing.JLabel();
        txtBuscarE = new javax.swing.JTextField();
        BotonCancelarE = new javax.swing.JLabel();
        BotonGuardarE = new javax.swing.JLabel();
        ComboGeneroE = new javax.swing.JComboBox<>();
        txtDocumentoE = new javax.swing.JTextField();
        txtNombreE = new javax.swing.JTextField();
        botonRegresarE = new javax.swing.JLabel();
        txtIdE = new javax.swing.JLabel();
        BotonActivoE = new javax.swing.JRadioButton();
        BotonInactivoE = new javax.swing.JRadioButton();
        barraEmpleado = new javax.swing.JScrollPane();
        TablaEmpleado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboSucursalE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tegucigalpa", "San Pedro Sula" }));
        ComboSucursalE.setOpaque(false);
        ComboSucursalE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSucursalEActionPerformed(evt);
            }
        });
        getContentPane().add(ComboSucursalE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 795, 264, 40));
        ComboSucursalE.getAccessibleContext().setAccessibleDescription("");

        ComboDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Pasaporte", "Licencia" }));
        ComboDocumento.setBorder(null);
        ComboDocumento.setOpaque(false);
        ComboDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 525, 264, 38));
        getContentPane().add(BotonCargoHistoricoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 170, 40));
        getContentPane().add(BotonSueldoHistoricoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 200, 170, 40));

        BotonEditarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEditarEMouseClicked(evt);
            }
        });
        getContentPane().add(BotonEditarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 170, 50));
        getContentPane().add(BotonAgregarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1121, 226, 100, 40));

        BotonBuscarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarEMouseClicked(evt);
            }
        });
        getContentPane().add(BotonBuscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 320, 40, 30));

        txtBuscarE.setBorder(null);
        txtBuscarE.setOpaque(false);
        txtBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarEActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 315, 340, 40));
        txtBuscarE.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(BotonCancelarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 110, 40));

        BotonGuardarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardarEMouseClicked(evt);
            }
        });
        getContentPane().add(BotonGuardarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 890, 100, 40));

        ComboGeneroE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        ComboGeneroE.setBorder(null);
        ComboGeneroE.setOpaque(false);
        getContentPane().add(ComboGeneroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 703, 264, 40));

        txtDocumentoE.setBorder(null);
        txtDocumentoE.setOpaque(false);
        txtDocumentoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoEActionPerformed(evt);
            }
        });
        getContentPane().add(txtDocumentoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 615, 262, 38));

        txtNombreE.setBorder(null);
        txtNombreE.setOpaque(false);
        txtNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 435, 262, 38));
        txtNombreE.getAccessibleContext().setAccessibleName("");

        botonRegresarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarEMouseClicked(evt);
            }
        });
        getContentPane().add(botonRegresarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 70, 160, 30));

        txtIdE.setEnabled(false);
        getContentPane().add(txtIdE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 140, 30));

        BotonActivoE.setText("Activo");
        BotonActivoE.setOpaque(false);
        getContentPane().add(BotonActivoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        BotonInactivoE.setText("Inactivo");
        BotonInactivoE.setOpaque(false);
        BotonInactivoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInactivoEActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInactivoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        TablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre Completo", "Tipo de Documento", "Documento", "Generp", "Sucursal", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        barraEmpleado.setViewportView(TablaEmpleado);

        getContentPane().add(barraEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 760, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/Pantalla Empleados.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1350, 970));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoEActionPerformed

    private void ComboDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDocumentoActionPerformed

    private void txtBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarEActionPerformed

    private void txtNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEActionPerformed

    private void ComboSucursalEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSucursalEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSucursalEActionPerformed

    private void BotonBuscarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarEMouseClicked

    private void botonRegresarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarEMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        this.dispose();

    }//GEN-LAST:event_botonRegresarEMouseClicked

    private void BotonGuardarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarEMouseClicked

        String Nombre = txtNombreE.getText();
        int tpDoc = ComboDocumento.getSelectedIndex();
        String Documento = txtDocumentoE.getText();
        int Genero = ComboGeneroE.getSelectedIndex();
        int Sucursal = ComboSucursalE.getSelectedIndex();

        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("Insert into Empleados (Nombre, Id_Genero,Documento,Id_Sucursal, estado, Id_TipoDocumento) VALUES(?,?,?,?,?,?)");
            ps.setString(1, Nombre);
            ps.setInt(2, Genero);
            ps.setString(3, Documento);
             ps.setInt(4, Sucursal);
              ps.setString(5, "Activo");
            ps.setInt(6, tpDoc);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro guardado");
            cargartabla();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_BotonGuardarEMouseClicked

    private void BotonEditarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEditarEMouseClicked
                                         
        int Id = Integer.parseInt(txtIdE.getText());
        String Nombre = txtNombreE.getText();
        int Documento = ComboDocumento.getSelectedIndex();
        String TipoDocumento = txtDocumentoE.getText();
        int Genero = ComboGeneroE.getSelectedIndex();
         int Sucursal = ComboSucursalE.getSelectedIndex();
        
        String Estado = "";

        if (BotonActivoE.isSelected() == true) {
            Estado = "Activo";
        } else if (BotonInactivoE.isSelected() == true) {
            Estado = "Inactivo";
    }//GEN-LAST:event_BotonEditarEMouseClicked

    private void BotonInactivoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInactivoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInactivoEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonActivoE;
    private javax.swing.JLabel BotonAgregarE;
    private javax.swing.JLabel BotonBuscarE;
    private javax.swing.JLabel BotonCancelarE;
    private javax.swing.JLabel BotonCargoHistoricoE;
    private javax.swing.JLabel BotonEditarE;
    private javax.swing.JLabel BotonGuardarE;
    private javax.swing.JRadioButton BotonInactivoE;
    private javax.swing.JLabel BotonSueldoHistoricoE;
    private javax.swing.JComboBox<String> ComboDocumento;
    private javax.swing.JComboBox<String> ComboGeneroE;
    private javax.swing.JComboBox<String> ComboSucursalE;
    private javax.swing.JTable TablaEmpleado;
    private javax.swing.JScrollPane barraEmpleado;
    private javax.swing.JLabel botonRegresarE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtBuscarE;
    private javax.swing.JTextField txtDocumentoE;
    private javax.swing.JLabel txtIdE;
    private javax.swing.JTextField txtNombreE;
    // End of variables declaration//GEN-END:variables

    private void cargartabla()  {
        DefaultTableModel modeloTabla = (DefaultTableModel) TablaEmpleado.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("Select E.Id_Empleado, E.Nombre, TD.Id_Documento, TD.Tipo_Documento, G.Genero, S.Nombre, E.Estado\n"
                    + "From Empleados as E\n"
                    + "INNER JOIN Tipo_Documento AS TD ON E.Id_TipoDocumento = TD.Id_Documento\n"
                    + "INNER JOIN Genero AS G ON E.Id_Genero = G.Id_Genero\n"
                    + "INNER JOIN Sucursal AS S ON E.Id_Sucursal = S.Id_Sucursal\n"
                    + "Order By E.Id_Empleado");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();

            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }

    public class Cargarg {

        public DefaultComboBoxModel getvalues() {

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            try {
                Connection con = Conexion.getConexion();
                String sql = "select Genero from Genero";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                }
                con.close();
                rs.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            return modelo;
        }
    }

    public class CargarSucursal {

        public DefaultComboBoxModel getvalues() {

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            try {
                Connection con = Conexion.getConexion();
                String sql = "select Nombre from sucursal";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                }
                con.close();
                rs.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            return modelo;
        }
    }

    public class CargarTDocumento {

        public DefaultComboBoxModel getvalues() {

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            try {
                Connection con = Conexion.getConexion();
                String sql = "select Tipo_Documento from Tipo_Documento";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    modelo.addElement(rs.getString(1));
                }
                con.close();
                rs.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            return modelo;
        }
    }
}
