/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_SAG;

import java.util.List;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Allisson Castro
 */
public class Login extends javax.swing.JFrame {

 /**
     * Creates new form Login2
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInicio = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        cover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
        });
        getContentPane().add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 490, 265, 65));

        txtUsuario.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 195, 330, 70));

        txtContrasena.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtContrasena.setBorder(null);
        txtContrasena.setOpaque(false);
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 325, 330, 70));

        cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/Login.jpeg"))); // NOI18N
        cover.setMaximumSize(new java.awt.Dimension(1300, 600));
        cover.setPreferredSize(new java.awt.Dimension(1300, 600));
        getContentPane().add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
       String  Usuario = "";
       String  Contraseña = "";
       
       String Pass  =  new  String(txtContrasena.getPassword());{
        
        
        if (txtUsuario.getText().equals(Usuario) && Pass.equals(Contraseña)) {
                   MenuPrincipal  MP = new MenuPrincipal ();
                   MP.setVisible(true);
                   dispose ();
         
                  } 
                   else{
                   {
            
                 JOptionPane.showMessageDialog(this, "Usuario/contraseña es incorrecto");
                     
                     } 
                   
                   
                   
   
          
          
          
          
       }
         
     
           
       }
              
    }//GEN-LAST:event_botonInicioMouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
    
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonInicio;
    private javax.swing.JLabel cover;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
