/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_SAG;

/**
 *
 * @author Allisson Castro
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresarP = new javax.swing.JLabel();
        botonAgregarP = new javax.swing.JLabel();
        botonEditarP = new javax.swing.JLabel();
        botonGuardarP = new javax.swing.JLabel();
        botonCancelarP = new javax.swing.JLabel();
        botonRestringirP = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtDescripcionP = new javax.swing.JTextField();
        txtCantidadP = new javax.swing.JTextField();
        ComboCategoriaP = new javax.swing.JComboBox<>();
        ComboPresentacionP = new javax.swing.JComboBox<>();
        txtxTamañosP = new javax.swing.JTextField();
        txtLoteP = new javax.swing.JTextField();
        txtFechaVencimientoP = new com.toedter.calendar.JDateChooser();
        txtBuscarP = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(botonRegresarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 40));
        getContentPane().add(botonAgregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 130, 30));
        getContentPane().add(botonEditarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 40));
        getContentPane().add(botonGuardarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 120, 40));
        getContentPane().add(botonCancelarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 120, 30));
        getContentPane().add(botonRestringirP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 120, 30));

        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 270, 190, 30));

        txtDescripcionP.setBorder(null);
        txtDescripcionP.setOpaque(false);
        getContentPane().add(txtDescripcionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 314, 190, 30));

        txtCantidadP.setBorder(null);
        txtCantidadP.setOpaque(false);
        getContentPane().add(txtCantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 450, 190, 30));

        ComboCategoriaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboCategoriaP.setBorder(null);
        ComboCategoriaP.setOpaque(false);
        getContentPane().add(ComboCategoriaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 360, 190, 30));

        ComboPresentacionP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboPresentacionP.setBorder(null);
        ComboPresentacionP.setOpaque(false);
        getContentPane().add(ComboPresentacionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 403, 190, 30));

        txtxTamañosP.setBorder(null);
        getContentPane().add(txtxTamañosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 494, 190, 30));

        txtLoteP.setBorder(null);
        txtLoteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLotePActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 540, 190, 30));

        txtFechaVencimientoP.setOpaque(false);
        getContentPane().add(txtFechaVencimientoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 580, 190, 32));

        txtBuscarP.setBorder(null);
        txtBuscarP.setOpaque(false);
        txtBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 240, 30));

        txtNombreProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/Pantalla Productos.png"))); // NOI18N
        getContentPane().add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtLotePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLotePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLotePActionPerformed

    private void txtBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCategoriaP;
    private javax.swing.JComboBox<String> ComboPresentacionP;
    private javax.swing.JLabel botonAgregarP;
    private javax.swing.JLabel botonCancelarP;
    private javax.swing.JLabel botonEditarP;
    private javax.swing.JLabel botonGuardarP;
    private javax.swing.JLabel botonRegresarP;
    private javax.swing.JLabel botonRestringirP;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtBuscarP;
    private javax.swing.JTextField txtCantidadP;
    private javax.swing.JTextField txtDescripcionP;
    private com.toedter.calendar.JDateChooser txtFechaVencimientoP;
    private javax.swing.JTextField txtLoteP;
    private javax.swing.JLabel txtNombreProducto;
    private javax.swing.JTextField txtxTamañosP;
    // End of variables declaration//GEN-END:variables
}
