/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_SAG;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Allisson Castro
 */




public class Sucursales extends javax.swing.JFrame {

    /**
     * Creates new form Sucursales
     */
    public Sucursales() {
        initComponents();
        cargartabla();
        txtIdS.setVisible(Boolean.FALSE);
        BotonActivoS.setVisible(Boolean.FALSE);
        BotonInactivoS.setVisible(Boolean.FALSE);
        txtEstadoS.setVisible(Boolean.FALSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonInactivoS = new javax.swing.JRadioButton();
        BotonActivoS = new javax.swing.JRadioButton();
        botonBuscarS = new javax.swing.JLabel();
        botonAgregarS = new javax.swing.JLabel();
        botonEditarS = new javax.swing.JLabel();
        botonGerenciaS = new javax.swing.JLabel();
        txtBuscarS = new javax.swing.JTextField();
        botonGuardarS = new javax.swing.JLabel();
        botonCancelarS = new javax.swing.JLabel();
        txtNombreS = new javax.swing.JTextField();
        txtDireccionS = new javax.swing.JTextField();
        botonCiudadS = new javax.swing.JComboBox<>();
        txtTelefonoS = new javax.swing.JTextField();
        botonSalirS = new javax.swing.JLabel();
        txtIdS = new javax.swing.JLabel();
        botonRegresarS = new javax.swing.JLabel();
        txtEstadoS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablasucursal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonInactivoS.setText("Inactivo");
        BotonInactivoS.setOpaque(false);
        BotonInactivoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInactivoSActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInactivoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        BotonActivoS.setText("Activo");
        BotonActivoS.setOpaque(false);
        BotonActivoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActivoSActionPerformed(evt);
            }
        });
        getContentPane().add(BotonActivoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));
        getContentPane().add(botonBuscarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 280, 40, 40));

        botonAgregarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarSMouseClicked(evt);
            }
        });
        getContentPane().add(botonAgregarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, 50));

        botonEditarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarSMouseClicked(evt);
            }
        });
        getContentPane().add(botonEditarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 170, 50));

        botonGerenciaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGerenciaSMouseClicked(evt);
            }
        });
        getContentPane().add(botonGerenciaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 190, 60));

        txtBuscarS.setBorder(null);
        txtBuscarS.setOpaque(false);
        txtBuscarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarSActionPerformed(evt);
            }
        });
        txtBuscarS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarSKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 285, 330, 40));

        botonGuardarS.setEnabled(false);
        botonGuardarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarSMouseClicked(evt);
            }
        });
        getContentPane().add(botonGuardarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 820, 120, 50));

        botonCancelarS.setEnabled(false);
        botonCancelarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarSMouseClicked(evt);
            }
        });
        getContentPane().add(botonCancelarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 820, 120, 50));

        txtNombreS.setBorder(null);
        txtNombreS.setEnabled(false);
        txtNombreS.setOpaque(false);
        txtNombreS.setVerifyInputWhenFocusTarget(false);
        txtNombreS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreSMousePressed(evt);
            }
        });
        txtNombreS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 262, 40));

        txtDireccionS.setBorder(null);
        txtDireccionS.setEnabled(false);
        txtDireccionS.setOpaque(false);
        txtDireccionS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionSMousePressed(evt);
            }
        });
        txtDireccionS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionSActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccionS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 263, 40));

        botonCiudadS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad", "Tegucigalpa", "San Pedro Sula" }));
        botonCiudadS.setBorder(null);
        botonCiudadS.setEnabled(false);
        botonCiudadS.setOpaque(false);
        botonCiudadS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCiudadSMousePressed(evt);
            }
        });
        getContentPane().add(botonCiudadS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 262, 40));
        botonCiudadS.getAccessibleContext().setAccessibleName("");

        txtTelefonoS.setBorder(null);
        txtTelefonoS.setEnabled(false);
        txtTelefonoS.setOpaque(false);
        txtTelefonoS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoSMousePressed(evt);
            }
        });
        txtTelefonoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoSActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefonoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 265, 40));
        getContentPane().add(botonSalirS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 530, 90, 40));

        txtIdS.setEnabled(false);
        getContentPane().add(txtIdS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 90, 20));

        botonRegresarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarSMouseClicked(evt);
            }
        });
        getContentPane().add(botonRegresarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 50));

        txtEstadoS.setText("Estado");
        getContentPane().add(txtEstadoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 70, 20));

        tablasucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cuidad", "Direccion", "Telefono", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablasucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablasucursalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablasucursal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 880, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/Pantalla Sucursales.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtBuscarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarSActionPerformed

    private void txtDireccionSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionSActionPerformed

    private void txtNombreSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSActionPerformed

    private void txtTelefonoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoSActionPerformed

    private void botonRegresarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarSMouseClicked
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        this.dispose();                
       

    }//GEN-LAST:event_botonRegresarSMouseClicked

    private void botonAgregarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarSMouseClicked
       Habillitar();
        
    }//GEN-LAST:event_botonAgregarSMouseClicked

    private void botonEditarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarSMouseClicked
        int Id = Integer.parseInt(txtIdS.getText());
        String Nombre= txtNombreS.getText();
        String Ciudad= botonCiudadS.getSelectedItem().toString();
        String Direccion= txtDireccionS.getText();
        String Telefono= txtTelefonoS.getText();
         String Estado= "";
         
          if (BotonActivoS.isSelected()== true){
                  Estado = "Activo";
               }    
              else if(BotonInactivoS.isSelected()== true){
                  Estado = "Inactivo";
              }

            try{
               Connection con = Conexion.getConexion();
               PreparedStatement ps = con.prepareStatement("Update Sucursal set Nombre=?, Ciudad=?, Direccion=?, Telefono=?, estado=? where Id_Sucursal =?");
               ps.setString(1, Nombre);
               ps.setString (2, Ciudad);
               ps.setString(3, Direccion);
               ps.setInt(4, Integer.valueOf(Telefono));
               ps.setString(5, Estado);
               ps.setInt(6, Id);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Registro Actualizado");
               cargartabla();
               BotonActivoS.setVisible(Boolean.TRUE);
               BotonInactivoS.setVisible(Boolean.TRUE);
               txtEstadoS.setVisible(Boolean.TRUE);


           }catch (SQLException ex){
               JOptionPane.showMessageDialog(null, ex.toString());
           }
            
    }//GEN-LAST:event_botonEditarSMouseClicked

    private void botonGerenciaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGerenciaSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGerenciaSMouseClicked

    private void BotonActivoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActivoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActivoSActionPerformed

    private void BotonInactivoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInactivoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInactivoSActionPerformed

    private void botonGuardarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarSMouseClicked
        // TODO add your handling code here:
        
        String Nombre= txtNombreS.getText();
        String Ciudad= botonCiudadS.getSelectedItem().toString();
        String Direccion= txtDireccionS.getText();
        String Telefono= txtTelefonoS.getText();
         
       
            try{
               Connection con = Conexion.getConexion();
               PreparedStatement ps = con.prepareStatement("Insert into Sucursal (Nombre, Ciudad, Direccion, Telefono, estado) VALUES(?,?,?,?,?)");
               ps.setString(1, Nombre);
               ps.setString (2, Ciudad);
               ps.setString(3, Direccion);
               ps.setInt(4, Integer.valueOf(Telefono));
               ps.setString(5, "Activo");
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Registro guardado");
               cargartabla();

           }catch (SQLException ex){
               JOptionPane.showMessageDialog(null, ex.toString());
           }

 
               
       
    }//GEN-LAST:event_botonGuardarSMouseClicked

    private void tablasucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablasucursalMouseClicked
        // TODO add your handling code here:
           try{
         int fila=tablasucursal.getSelectedRow();
         int id= Integer.parseInt(tablasucursal.getValueAt(fila, 0).toString());
         PreparedStatement ps;
         ResultSet rs;
         Connection con = Conexion.getConexion();
         ps = con.prepareStatement("SELECT  Nombre, Ciudad, Direccion, Telefono, estado FROM Sucursal WHERE Id_Sucursal=?");
         ps.setInt(1, id);
         rs = ps.executeQuery();
         
           
          while (rs.next()){
              txtIdS.setText(String.valueOf(id));
             txtNombreS.setText(rs.getString("Nombre"));
             botonCiudadS.setSelectedItem(rs.getString("Ciudad"));
             txtDireccionS.setText(rs.getString("Direccion"));
             txtTelefonoS.setText(rs.getString("Telefono"));
          if (rs.getString("estado").equals("Activo")){
              BotonActivoS.setSelected(true);
           }    
          else if(rs.getString("estado").equals("Inactivo")){
              BotonInactivoS.setSelected(true);
          }
          }
          
               System.out.println(txtIdS.getText());
           Habillitar();
       }catch (SQLException ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }
           
    }//GEN-LAST:event_tablasucursalMouseClicked

    private void botonCancelarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarSMouseClicked
       
        Limpiar ();
      
       
    }//GEN-LAST:event_botonCancelarSMouseClicked

    private void txtNombreSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreSMousePressed
        if (txtNombreS.isEnabled()== false){
       
            JOptionPane.showMessageDialog(null, "Dar Click en Agregar o Editar para utilizar el campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_txtNombreSMousePressed

    private void botonCiudadSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCiudadSMousePressed
          if (botonCiudadS.isEnabled()== false){
       
            JOptionPane.showMessageDialog(null, "Dar Click en Agregar o Editar para utilizar el campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_botonCiudadSMousePressed

    private void txtDireccionSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionSMousePressed
          if (txtDireccionS.isEnabled()== false){
       
            JOptionPane.showMessageDialog(null, "Dar Click en Agregar o Editar para utilizar el campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_txtDireccionSMousePressed

    private void txtTelefonoSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoSMousePressed
          if (txtTelefonoS.isEnabled()== false){
       
            JOptionPane.showMessageDialog(null, "Dar Click en Agregar o Editar para utilizar el campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_txtTelefonoSMousePressed

    private void txtBuscarSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSKeyPressed
      
       
    }//GEN-LAST:event_txtBuscarSKeyPressed

    private void txtBuscarSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSKeyTyped
        buscarData(txtBuscarS.getText());
    }//GEN-LAST:event_txtBuscarSKeyTyped
private void cargartabla(){
       DefaultTableModel modeloTabla= (DefaultTableModel) tablasucursal.getModel();
       modeloTabla.setRowCount(0);
       
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
       
         try{
           Connection con = Conexion.getConexion();
           ps = con.prepareStatement("SELECT Id_Sucursal, Nombre, Ciudad, Direccion, Telefono, estado FROM Sucursal");
          rs = ps.executeQuery();
          rsmd= rs.getMetaData();
          columnas = rsmd.getColumnCount();
           
          while (rs.next()){
              Object[] fila= new Object[columnas];
              for (int indice=0; indice<columnas; indice++){
                  fila[indice] = rs.getObject(indice + 1);
              }
              modeloTabla.addRow(fila);
          }
          
         // JOptionPane.showMessageDialog(null, "Registro guardado");
           
       }catch (SQLException ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonActivoS;
    private javax.swing.JRadioButton BotonInactivoS;
    private javax.swing.JLabel botonAgregarS;
    private javax.swing.JLabel botonBuscarS;
    private javax.swing.JLabel botonCancelarS;
    private javax.swing.JComboBox<String> botonCiudadS;
    private javax.swing.JLabel botonEditarS;
    private javax.swing.JLabel botonGerenciaS;
    private javax.swing.JLabel botonGuardarS;
    private javax.swing.JLabel botonRegresarS;
    private javax.swing.JLabel botonSalirS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablasucursal;
    private javax.swing.JTextField txtBuscarS;
    private javax.swing.JTextField txtDireccionS;
    private javax.swing.JLabel txtEstadoS;
    private javax.swing.JLabel txtIdS;
    private javax.swing.JTextField txtNombreS;
    private javax.swing.JTextField txtTelefonoS;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        //row new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        txtIdS.setText("");
        txtNombreS.setText("");
        botonCiudadS.setSelectedIndex(-1);
        txtDireccionS.setText("");
        txtTelefonoS.setText("");
        BotonActivoS.setVisible(Boolean.FALSE);
        BotonInactivoS.setVisible(Boolean.FALSE);
        txtEstadoS.setVisible(Boolean.FALSE);
    }
    
    void buscarData(String valor) {
        String[] titulos = {"ID", "Nombre", "Ciudad", "Direccion", "Telefono",  "Estado"};
        String[] registros = new String[13];
        String sql = "SELECT Id_Sucursal,Nombre,Ciudad,Direccion, Telefono,estado\n"
                + "FROM Sucursal \n"
                + "WHERE CONCAT (Id_Sucursal, ' ', Nombre) LIKE '%" + valor + "%'\n"
                + "ORDER BY Id_Sucursal";

         DefaultTableModel model = new DefaultTableModel(null, titulos);
         Connection con = Conexion.getConexion();

        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                registros[0] = rs.getString("Id_Sucursal");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("Ciudad");
                registros[3] = rs.getString("Direccion");
                registros[4] = rs.getString("Telefono");
                registros[5] = rs.getString("estado");
                
                model.addRow(registros);
            }

            tablasucursal.setModel(model);
           // anchoColumnas();
        } catch (SQLException ex) {
            Logger.getLogger(Sucursales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void Habillitar() {
        //row new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       
        txtNombreS.enable(Boolean.TRUE);
        botonCiudadS.enable(Boolean.TRUE);
        txtDireccionS.enable(Boolean.TRUE);
        txtTelefonoS.enable(Boolean.TRUE);
     
    }
    
}
